#!/usr/bin/env python3
"""
GPU Worker for AR-3 Research Platform
Runs on Vast.ai instance, polls for GPU jobs and executes them.

The worker receives GPU commands (Python/PyTorch code) generated by the LLM
and executes them on the RTX 3060 GPU.

Usage: python3 gpu_worker.py [--poll-interval 3]
"""

import json
import os
import sys
import time
import subprocess
import traceback
from datetime import datetime
from pathlib import Path

JOB_QUEUE_FILE = '/tmp/gpu_jobs.json'
JOB_RESULTS_FILE = '/tmp/gpu_results.json'
POLL_INTERVAL = 3  # seconds

def log(msg):
    print(f"[GPU Worker {datetime.now().isoformat()}] {msg}", flush=True)

def read_queue():
    try:
        if not os.path.exists(JOB_QUEUE_FILE):
            return []
        with open(JOB_QUEUE_FILE, 'r') as f:
            return json.load(f)
    except Exception as e:
        log(f"Error reading queue: {e}")
        return []

def write_queue(jobs):
    try:
        with open(JOB_QUEUE_FILE, 'w') as f:
            json.dump(jobs, f, indent=2)
    except Exception as e:
        log(f"Error writing queue: {e}")

def read_results():
    try:
        if not os.path.exists(JOB_RESULTS_FILE):
            return {}
        with open(JOB_RESULTS_FILE, 'r') as f:
            return json.load(f)
    except Exception as e:
        log(f"Error reading results: {e}")
        return {}

def write_results(results):
    try:
        with open(JOB_RESULTS_FILE, 'w') as f:
            json.dump(results, f, indent=2)
    except Exception as e:
        log(f"Error writing results: {e}")

def execute_python_code(code: str) -> dict:
    """Execute Python code and return result/error."""
    log(f"Executing Python code ({len(code)} chars)")
    
    # Write code to a temp file
    code_file = f"/tmp/gpu_code_{int(time.time()*1000)}.py"
    with open(code_file, 'w') as f:
        f.write(code)
    
    try:
        # Execute with python3, capturing output
        result = subprocess.run(
            ['python3', code_file],
            capture_output=True,
            text=True,
            timeout=300,  # 5 min timeout
            cwd='/tmp'
        )
        
        os.unlink(code_file)
        
        if result.returncode == 0:
            return {
                'success': True,
                'output': result.stdout.strip(),
                'error': None,
            }
        else:
            return {
                'success': False,
                'output': result.stdout.strip(),
                'error': result.stderr.strip() or f'Exit code: {result.returncode}',
            }
    except subprocess.TimeoutExpired:
        os.unlink(code_file)
        return {
            'success': False,
            'output': '',
            'error': 'Code execution timed out (5 min limit)',
        }
    except Exception as e:
        try:
            os.unlink(code_file)
        except:
            pass
        return {
            'success': False,
            'output': '',
            'error': f"Execution error: {str(e)}\n{traceback.format_exc()}",
        }

def execute_gpu_command(job: dict) -> dict:
    """Execute a GPU command from the job queue."""
    job_id = job['jobId']
    stage_name = job['stageName']
    prompt = job.get('prompt', '')  # This is the LLM's instruction for GPU work
    context = job.get('context', '')
    
    log(f"Processing GPU job {job_id}: stage={stage_name}")
    log(f"Prompt length: {len(prompt)} chars")
    
    try:
        # Try to extract JSON from the prompt (LLM response may contain natural language + JSON)
        # Look for JSON object pattern: {...}
        gpu_command = None
        
        # Try direct JSON parse first (including if LLM wrapped code in JSON)
        gpu_command = None
        try:
            gpu_command = json.loads(prompt.strip())
        except json.JSONDecodeError:
            pass
        
        # If not valid JSON, look for JSON with code inside (possibly wrapped in markdown)
        if not gpu_command or not isinstance(gpu_command.get('code'), str):
            import re
            # Try to find JSON object with action and code fields (code may be wrapped in ```python ... ```)
            json_pattern = r'\{"action":\s*"run_python"[^{}]*(?:"code":\s*)?([^{}]*(?:\{[^{}]*\}[^{}]*)*)'
            matches = re.findall(json_pattern, prompt, re.DOTALL)
            for m in matches:
                # Extract code from markdown code blocks if present
                code_match = re.search(r'```python\s*(.*?)```', m, re.DOTALL)
                if code_match:
                    gpu_command = {"action": "run_python", "code": code_match.group(1).strip()}
                    break
        
        # If still no valid GPU command, look for code blocks
        if not gpu_command or not isinstance(gpu_command.get('code'), str):
            import re
            # Find ALL python code blocks
            code_blocks = re.findall(r'```python\s+(.*?)\s+```', prompt, re.DOTALL)
            if code_blocks:
                # Use the largest code block
                biggest = max(code_blocks, key=len).strip()
                if len(biggest) > 20:  # Only use if substantial
                    gpu_command = {"action": "run_python", "code": biggest}
            else:
                # Look for any code-looking content (import statements, def, class, torch., etc.)
                code_indicators = re.findall(r'(?:import\s+\w+|from\s+\w+\s+import|def\s+\w+|class\s+\w+|torch\.|cuda|tensor\()', prompt)
                if code_indicators:
                    # Try to extract a contiguous block of code-ish lines
                    lines = prompt.split('\n')
                    code_lines = []
                    in_code = False
                    for line in lines:
                        stripped = line.strip()
                        # Skip markdown headers, lists, plain text
                        if stripped.startswith('#') or stripped.startswith('- ') or stripped.startswith('* ') or stripped.startswith('1.') or stripped.startswith('2.') or not stripped:
                            if in_code:
                                in_code = False
                            continue
                        if any(ind in stripped for ind in ['import ', 'from ', 'def ', 'class ', 'torch.', 'cuda', 'tensor']):
                            in_code = True
                            code_lines.append(stripped)
                        elif in_code:
                            code_lines.append(stripped)
                    if code_lines:
                        gpu_command = {"action": "run_python", "code": '\n'.join(code_lines)}
        
        if not gpu_command or not isinstance(gpu_command.get('code'), str) or len(gpu_command.get('code', '')) < 10:
            # Nothing useful found, run nvidia-smi
            gpu_command = {"action": "nvidia_smi"}
        
        action = gpu_command.get('action', 'run_python')
        
        if action == 'run_python':
            code = gpu_command.get('code', '')
            if not code or len(code) < 10:
                return {
                    'success': False,
                    'output': '',
                    'error': 'No valid Python code found in LLM response',
                }
            log(f"Running Python code, {len(code)} chars")
            result = execute_python_code(code)
            
        elif action == 'run_bash':
            cmd = gpu_command.get('command', gpu_command.get('cmd', ''))
            log(f"Running bash command: {cmd[:100]}")
            result = subprocess.run(
                cmd, shell=True, capture_output=True, text=True, timeout=120
            )
            result = {
                'success': result.returncode == 0,
                'output': result.stdout.strip(),
                'error': result.stderr.strip() if result.returncode != 0 else None,
            }
            
        elif action == 'nvidia_smi':
            result = subprocess.run(
                ['nvidia-smi', '--query-gpu=name,memory.total,memory.used,utilization.gpu,utilization.memory', '--format=csv,noheader,nounits'],
                capture_output=True, text=True, timeout=10
            )
            gpu_info = result.stdout.strip().split(', ')
            result = {
                'success': True,
                'output': json.dumps({
                    'gpu_name': gpu_info[0],
                    'memory_total_mb': gpu_info[1],
                    'memory_used_mb': gpu_info[2],
                    'gpu_utilization': gpu_info[3] + '%',
                    'memory_utilization': gpu_info[4] + '%',
                }),
                'error': None,
            }
        else:
            result = {
                'success': False,
                'output': '',
                'error': f"Unknown GPU action: {action}. Supported: run_python, run_bash, nvidia_smi",
            }
        
        return result
        
    except Exception as e:
        return {
            'success': False,
            'output': '',
            'error': f"GPU command failed: {str(e)}\n{traceback.format_exc()}",
        }

def process_jobs():
    queue = read_queue()
    results = read_results()
    
    processed = False
    for job in queue:
        if job.get('status') == 'pending':
            # Mark as running
            job['status'] = 'running'
            job['startedAt'] = datetime.now().isoformat()
            write_queue(queue)
            
            log(f"Executing GPU job {job['jobId']}")
            
            # Execute the GPU command
            result = execute_gpu_command(job)
            
            # Store result
            results[job['jobId']] = {
                'jobId': job['jobId'],
                'output': result.get('output', ''),
                'error': result.get('error'),
                'success': result.get('success', False),
                'completedAt': datetime.now().isoformat(),
            }
            
            # Update job status in queue
            for j in queue:
                if j['jobId'] == job['jobId']:
                    j['status'] = 'completed'
                    j['completedAt'] = datetime.now().isoformat()
                    break
            
            write_queue(queue)
            write_results(results)
            processed = True
            
            if result.get('success'):
                log(f"Job {job['jobId']} succeeded: {str(result.get('output',''))[:100]}")
            else:
                log(f"Job {job['jobId']} failed: {result.get('error', 'unknown')}")
    
    return processed

def main():
    log(f"GPU Worker started. Polling every {POLL_INTERVAL}s")
    
    # Verify GPU
    try:
        result = subprocess.run(
            ['nvidia-smi', '--query-gpu=name,driver_version,memory.total', '--format=csv,noheader'],
            capture_output=True, text=True, timeout=10
        )
        if result.returncode == 0:
            log(f"GPU detected: {result.stdout.strip()}")
        else:
            log("WARNING: nvidia-smi failed")
    except Exception as e:
        log(f"ERROR: Could not detect GPU: {e}")
        sys.exit(1)
    
    # Main loop
    while True:
        try:
            processed = process_jobs()
            if not processed:
                time.sleep(POLL_INTERVAL)
        except KeyboardInterrupt:
            log("GPU Worker stopped.")
            break
        except Exception as e:
            log(f"Error in main loop: {e}")
            time.sleep(POLL_INTERVAL)

if __name__ == '__main__':
    main()
